### ISSUE TITLE
Travis builds are failing with libboost error

### ISSUE THREAD

**Issue by nickbroon** [tumi8/vermont#128]
The last build of the master branch from 3 months ago is fine, but if you trigger a new build of the branch it fails for some compiler combinations. https://travis-ci.org/tumi8/vermont/branches

```
[ 89%] Linking CXX executable vermont
/usr/local/cmake-3.12.4/bin/cmake -E cmake_link_script CMakeFiles/vermont.dir/link.txt --verbose=1
/usr/lib/ccache/g++-6   -std=gnu++11 -Werror -Wall -pedantic -Wextra -Wno-unused-parameter -O2 -g -DNDEBUG  -rdynamic CMakeFiles/vermont.dir/src/vermont.cc.o  -o vermont src/modules/libmodules.a src/core/libcore.a src/common/anon/libanon.a src/common/ipfixlolib/libipfixlolib.a src/common/libcommon.a src/osdep/libosdep.a -lpthread -lsystemd -lczmq -lboost_regex -lboost_filesystem -lboost_system -lxml2 -lpcap -lpcap -lssl -lcrypto 
src/modules/libmodules.a(RegExFilter.cpp.o): In function `boost::cpp_regex_traits<char>::transform_primary[abi:cxx11](char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:965: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
src/modules/libmodules.a(RegExFilter.cpp.o): In function `boost::cpp_regex_traits<char>::transform[abi:cxx11](char const*, char const*) const':
/usr/include/boost/regex/v4/cpp_regex_traits.hpp:961: undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
collect2: error: ld returned 1 exit status
CMakeFiles/vermont.dir/build.make:97: recipe for target 'vermont' failed
make[2]: *** [vermont] Error 1
make[2]: Target 'CMakeFiles/vermont.dir/build' not remade because of errors.
```

**Comment by nickbroon** [comment]
Possibly related to https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment

**Comment by constcast** [comment]
Yes, the problem is likely related to the compile flags for boost in Xenial. There are related bugs for Debian and Ubuntu:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823978
https://bugs.launchpad.net/ubuntu/+source/llvm-toolchain-3.8/+bug/1664321

I like the idea to bump the build environment to a newer Ubuntu version. However, Xenial is quite old as well. I am working on a branch that uses Bionic (18.04). Newer versions however also bump openssl to >= 1.1.0. 

I have  working port of Vermont that supports OpenSSL >= 1.1.0, but would drop support for < 1.1.0. Is there a need to still support the old versions of openssl, given that they are EOL for the non-enterprise use?

**Comment by constcast** [comment]
I have opened another pull request for this issue. It bumps the version for travis to Bionic and requires openssl 1.1.0 or newer. 

I cherry-picked your boost changes from pull request #133 

Can you have a look at the request?

**Comment by nickbroon** [comment]
Fab, thanks @constcast !
I'll have a review of your changes in your PR and comment there.
My main concern would be that Vermont still builds against Debian Stretch and Buster as they are base for the supported production environments I use.
